name: xrayvision

build:
    image: latest

python:
    version: 3.6

channels:
    - conda-forge

dependencies:
    - sunpy
    - Cython
    - matplotlib
    - numpy
    - pip:
        - sunpy-sphinx-theme
